2019-04-07 21:34:28,420 - [auto_add_mp.py:22] - ERROR - 123
NoneType: None
2019-04-07 21:34:45,624 - [auto_add_mp.py:22] - ERROR - 123
NoneType: None
2019-04-07 21:35:00,576 - [auto_add_mp.py:22] - ERROR - 123
NoneType: None
2019-04-07 21:42:40,235 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 21:44:07,127 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 21:44:07,129 - [api.py:207] - ERROR - 123
NoneType: None
2019-04-07 21:58:00,066 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 22:23:41,014 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 22:24:20,296 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 22:24:43,460 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 22:25:32,384 - [basic.py:168] - ERROR - 出现验证码。。。
2019-04-07 22:25:36,685 - [basic.py:257] - ERROR - verify code ocr: 解封成功，正在为您跳转来源地址...
2019-04-07 22:31:53,676 - [updatemp.py:61] - ERROR - 123
2019-04-07 22:32:15,311 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:32:44,747 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:33:44,495 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:33:44,495 - [api.py:197] - ERROR - 123
2019-04-07 22:34:40,382 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:34:40,382 - [api.py:208] - ERROR - Exception Logged
2019-04-07 22:34:50,811 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:34:50,811 - [api.py:208] - ERROR - Exception Logged
NoneType: None
2019-04-07 22:35:25,307 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-07 22:35:36,783 - [updatemp.py:61] - ERROR - 123
NoneType: None
2019-04-08 00:01:10,648 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:33,817 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:39,056 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:44,657 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:48,336 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:51,688 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:01:57,033 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 354, in down_html
TypeError: a bytes-like object is required, not 'str'
2019-04-08 00:05:33,312 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 353, in down_html
    code.write(html)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa5' in position 32413: illegal multibyte sequence
2019-04-08 00:17:13,334 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 82, in <module>
    index_html_path = wechats.down_html(wz_item['content_url'], wz_item['title'])
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 262, in down_html
    ct = re.findall('var ct = "(.*?)";', content)[0]
IndexError: list index out of range
2019-04-08 00:19:14,350 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 48, in <module>
    wz_list = wechats.get_gzh_message(url=wz_url)
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 210, in get_gzh_message
    raise WechatSogouException('get_gzh_message need param text and url')
wechatsogou.exceptions.WechatSogouException: get_gzh_message need param text and url
2019-04-08 00:19:16,350 - [updatemp.py:109] - ERROR - Exception Logged: updatemp
Traceback (most recent call last):
  File "C:/Users/Evan/Desktop/wechat_sogou_crawl/updatemp.py", line 48, in <module>
    wz_list = wechats.get_gzh_message(url=wz_url)
  File "C:\Users\Evan\Desktop\wechat_sogou_crawl\wechatsogou\api.py", line 210, in get_gzh_message
    raise WechatSogouException('get_gzh_message need param text and url')
wechatsogou.exceptions.WechatSogouException: get_gzh_message need param text and url
